"""Adds initial commit

Revision ID: 61870ce3406a
Revises: 
Create Date: 2024-10-08 15:11:23.373011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61870ce3406a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email-address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('backup_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emailaddress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('backup_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emailaddress')
    op.drop_table('email-address')
    # ### end Alembic commands ###
